Mac-specific linker flags.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -694,6 +694,8 @@ am__fastdepCXX_FALSE
 CXXCPP
 GREP
 EGREP
+MACOS_TRUE
+MACOS_FALSE
 CC
 CFLAGS
 ac_ct_CC
@@ -3792,6 +3794,14 @@ fi
 
 done
 
+ if test "$(uname -s)" = "Darwin"; then
+  MACOS_TRUE=
+  MACOS_FALSE='#'
+else
+  MACOS_TRUE='#'
+  MACOS_FALSE=
+fi
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -5183,6 +5193,13 @@ echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${MACOS_TRUE}" && test -z "${MACOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MACOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MACOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -5808,6 +5825,8 @@ am__fastdepCXX_FALSE!$am__fastdepCXX_FALSE$ac_delim
 CXXCPP!$CXXCPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
+MACOS_TRUE!$MACOS_TRUE$ac_delim
+MACOS_FALSE!$MACOS_FALSE$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
 ac_ct_CC!$ac_ct_CC$ac_delim
@@ -5819,7 +5838,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 87; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 89; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
